spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:/config/roomescape_prod/'
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.SQL: debug
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: roomescape
