spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: alsdnr12!#
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.SQL: debug
